# Generated by Django 3.0.8 on 2022-12-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('part', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=150)),
                ('team', models.CharField(max_length=30)),
                ('is_voted_demo', models.BooleanField(default=False)),
                ('is_voted_partleader', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
