# Generated by Django 3.0.8 on 2022-12-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partleader_vote',
            name='part',
            field=models.CharField(default='front', max_length=30),
        ),
    ]
