# Generated by Django 3.0.8 on 2022-12-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_partleader_vote_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partleader_vote',
            name='part',
            field=models.CharField(max_length=30),
        ),
    ]
